### PR TITLE
Added make.py support for copying files to the RoboRio

### PR DESCRIPTION
**Pull request by CSDotBro**
Copies over deploy files from a certain deploy folder onto the roboRio using rsync. Along with copying over these files, it also checks if rsync is installed on the roboRio and downloads and installs rsync and its various dependencies if it was found not to have been installed.

### CODE REVIEW

**Comment by CSDotBro** [comment]
The function to download NI packages is similar to how 971 does it.

https://github.com/calcmogul/971-partial-mirror/blob/master/aos/downloader/downloader.py

**Comment by CSDotBro** [comment]
This dependencies are still not official. Looking into if rsync has newer dependencies or still maintain the same ones.

**Comment by calcmogul** [comment]
The versions of rsync's dependencies should be those in the 2019 folder because all packages have to be built with the same glibc.

**Comment by CSDotBro** [comment]
> The versions of rsync's dependencies should be those in the 2019 folder because all packages have to be built with the same glibc.

Ok. They originally served as a placeholder so I can search for each library through the list. However, I found the updated libraries and replaced the outdated libraries.

**Comment by CSDotBro** [comment]
This patch is now pretty polished and ready to be tested on a spare roboRIO.

**Pull request closed without merging**
